# CIS Kubernetes Benchmark Policies
# Policies aligned with CIS Kubernetes Benchmark v1.8

---
# CIS 5.1.1 - Ensure cluster-admin role is only used where required
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cis-5-1-1-restrict-cluster-admin
  annotations:
    policies.kyverno.io/title: "CIS 5.1.1 - Restrict cluster-admin Role"
    policies.kyverno.io/category: CIS Kubernetes Benchmark
    policies.kyverno.io/severity: critical
    policies.kyverno.io/subject: ClusterRoleBinding
    policies.kyverno.io/description: >-
      CIS 5.1.1: The cluster-admin role provides full access to the cluster.
      Restrict its usage to only necessary service accounts.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: restrict-cluster-admin
      match:
        any:
          - resources:
              kinds:
                - ClusterRoleBinding
      validate:
        message: "CIS 5.1.1: Binding to cluster-admin role requires approval."
        pattern:
          roleRef:
            name: "!cluster-admin"

---
# CIS 5.1.3 - Minimize wildcard use in Roles and ClusterRoles
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cis-5-1-3-restrict-wildcards
  annotations:
    policies.kyverno.io/title: "CIS 5.1.3 - Minimize Wildcard Use"
    policies.kyverno.io/category: CIS Kubernetes Benchmark
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Role, ClusterRole
    policies.kyverno.io/description: >-
      CIS 5.1.3: Minimize wildcard use in Roles and ClusterRoles.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: restrict-wildcards
      match:
        any:
          - resources:
              kinds:
                - ClusterRole
                - Role
      exclude:
        any:
          - resources:
              names:
                - cluster-admin
                - admin
                - edit
                - view
                - system:*
      validate:
        message: "CIS 5.1.3: Wildcard (*) in verbs, resources, or apiGroups is not recommended."
        deny:
          conditions:
            any:
              - key: "*"
                operator: AnyIn
                value: "{{ request.object.rules[].verbs[] }}"
              - key: "*"
                operator: AnyIn
                value: "{{ request.object.rules[].resources[] }}"

---
# CIS 5.2.2 - Minimize the admission of privileged containers
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cis-5-2-2-disallow-privileged
  annotations:
    policies.kyverno.io/title: "CIS 5.2.2 - Disallow Privileged Containers"
    policies.kyverno.io/category: CIS Kubernetes Benchmark
    policies.kyverno.io/severity: critical
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      CIS 5.2.2: Do not generally permit containers to be run as privileged.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: disallow-privileged
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "CIS 5.2.2: Privileged containers are not allowed."
        pattern:
          spec:
            =(initContainers):
              - =(securityContext):
                  =(privileged): false
            containers:
              - =(securityContext):
                  =(privileged): false

---
# CIS 5.2.3 - Minimize the admission of containers wishing to share the host process ID namespace
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cis-5-2-3-disallow-host-pid
  annotations:
    policies.kyverno.io/title: "CIS 5.2.3 - Disallow Host PID"
    policies.kyverno.io/category: CIS Kubernetes Benchmark
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      CIS 5.2.3: Do not generally permit containers to share the host process ID namespace.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: disallow-host-pid
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "CIS 5.2.3: Sharing host PID namespace is not allowed."
        pattern:
          spec:
            =(hostPID): false

---
# CIS 5.2.4 - Minimize the admission of containers wishing to share the host IPC namespace
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cis-5-2-4-disallow-host-ipc
  annotations:
    policies.kyverno.io/title: "CIS 5.2.4 - Disallow Host IPC"
    policies.kyverno.io/category: CIS Kubernetes Benchmark
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      CIS 5.2.4: Do not generally permit containers to share the host IPC namespace.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: disallow-host-ipc
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "CIS 5.2.4: Sharing host IPC namespace is not allowed."
        pattern:
          spec:
            =(hostIPC): false

---
# CIS 5.2.5 - Minimize the admission of containers wishing to share the host network namespace
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cis-5-2-5-disallow-host-network
  annotations:
    policies.kyverno.io/title: "CIS 5.2.5 - Disallow Host Network"
    policies.kyverno.io/category: CIS Kubernetes Benchmark
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      CIS 5.2.5: Do not generally permit containers to share the host network namespace.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: disallow-host-network
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "CIS 5.2.5: Sharing host network namespace is not allowed."
        pattern:
          spec:
            =(hostNetwork): false

---
# CIS 5.2.6 - Minimize the admission of containers with allowPrivilegeEscalation
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cis-5-2-6-disallow-privilege-escalation
  annotations:
    policies.kyverno.io/title: "CIS 5.2.6 - Disallow Privilege Escalation"
    policies.kyverno.io/category: CIS Kubernetes Benchmark
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      CIS 5.2.6: Do not generally permit containers with privilege escalation.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: disallow-privilege-escalation
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "CIS 5.2.6: Privilege escalation is not allowed."
        pattern:
          spec:
            =(initContainers):
              - securityContext:
                  allowPrivilegeEscalation: false
            containers:
              - securityContext:
                  allowPrivilegeEscalation: false

---
# CIS 5.2.7 - Minimize the admission of root containers
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cis-5-2-7-run-as-nonroot
  annotations:
    policies.kyverno.io/title: "CIS 5.2.7 - Run as Non-Root"
    policies.kyverno.io/category: CIS Kubernetes Benchmark
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      CIS 5.2.7: Do not generally permit containers to run as root.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: run-as-nonroot
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "CIS 5.2.7: Containers must run as non-root."
        anyPattern:
          - spec:
              securityContext:
                runAsNonRoot: true
          - spec:
              containers:
                - securityContext:
                    runAsNonRoot: true

---
# CIS 5.2.8 - Minimize the admission of containers with the NET_RAW capability
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cis-5-2-8-drop-net-raw
  annotations:
    policies.kyverno.io/title: "CIS 5.2.8 - Drop NET_RAW Capability"
    policies.kyverno.io/category: CIS Kubernetes Benchmark
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      CIS 5.2.8: Do not generally permit containers with NET_RAW capability.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: drop-net-raw
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "CIS 5.2.8: Containers must drop NET_RAW capability."
        pattern:
          spec:
            containers:
              - securityContext:
                  capabilities:
                    drop:
                      - NET_RAW

---
# CIS 5.2.9 - Minimize the admission of containers with added capabilities
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cis-5-2-9-restrict-capabilities
  annotations:
    policies.kyverno.io/title: "CIS 5.2.9 - Restrict Added Capabilities"
    policies.kyverno.io/category: CIS Kubernetes Benchmark
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      CIS 5.2.9: Do not generally permit containers with added capabilities.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: restrict-added-capabilities
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "CIS 5.2.9: Adding capabilities is restricted."
        pattern:
          spec:
            containers:
              - =(securityContext):
                  =(capabilities):
                    =(add): "NET_BIND_SERVICE | null"

---
# CIS 5.7.4 - The default namespace should not be used
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cis-5-7-4-disallow-default-namespace
  annotations:
    policies.kyverno.io/title: "CIS 5.7.4 - Disallow Default Namespace"
    policies.kyverno.io/category: CIS Kubernetes Benchmark
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      CIS 5.7.4: The default namespace should not be used.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: disallow-default-namespace
      match:
        any:
          - resources:
              kinds:
                - Pod
                - Service
                - ConfigMap
                - Secret
                - Deployment
                - StatefulSet
                - DaemonSet
      validate:
        message: "CIS 5.7.4: Resources should not be deployed in the default namespace."
        pattern:
          metadata:
            namespace: "!default"
