# Generation Policies - Clone Secrets and RBAC
# Automatically distributes secrets and creates RBAC resources

---
# Clone image pull secret to new namespaces
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: clone-image-pull-secret
  annotations:
    policies.kyverno.io/title: Clone Image Pull Secret
    policies.kyverno.io/category: Multi-Tenancy
    policies.kyverno.io/subject: Secret
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      Clones the image pull secret from a source namespace to all new namespaces.
      This ensures pods can pull images from private registries.
spec:
  rules:
    - name: clone-regcred
      match:
        any:
          - resources:
              kinds:
                - Namespace
      exclude:
        any:
          - resources:
              names:
                - kube-system
                - kube-public
                - kube-node-lease
                - default
                - kyverno
      generate:
        apiVersion: v1
        kind: Secret
        name: regcred
        namespace: "{{request.object.metadata.name}}"
        synchronize: true
        clone:
          namespace: default
          name: regcred

---
# Clone TLS secret to namespaces
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: clone-tls-secret
  annotations:
    policies.kyverno.io/title: Clone TLS Secret
    policies.kyverno.io/category: Multi-Tenancy
    policies.kyverno.io/subject: Secret
    policies.kyverno.io/description: >-
      Clones wildcard TLS certificate to namespaces that need it.
spec:
  rules:
    - name: clone-wildcard-tls
      match:
        any:
          - resources:
              kinds:
                - Namespace
              selector:
                matchLabels:
                  requires-tls: "true"
      generate:
        apiVersion: v1
        kind: Secret
        name: wildcard-tls
        namespace: "{{request.object.metadata.name}}"
        synchronize: true
        clone:
          namespace: cert-manager
          name: wildcard-tls

---
# Generate RoleBinding for namespace owner
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-rolebinding
  annotations:
    policies.kyverno.io/title: Generate RoleBinding
    policies.kyverno.io/category: Multi-Tenancy
    policies.kyverno.io/subject: RoleBinding
    policies.kyverno.io/description: >-
      Creates a RoleBinding granting admin access to the user who created
      the namespace.
spec:
  rules:
    - name: generate-owner-rolebinding
      match:
        any:
          - resources:
              kinds:
                - Namespace
      exclude:
        any:
          - resources:
              names:
                - kube-*
                - default
                - kyverno
      generate:
        apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        name: namespace-owner
        namespace: "{{request.object.metadata.name}}"
        data:
          metadata:
            labels:
              generated-by: kyverno
          subjects:
            - kind: User
              name: "{{request.userInfo.username}}"
              apiGroup: rbac.authorization.k8s.io
          roleRef:
            kind: ClusterRole
            name: admin
            apiGroup: rbac.authorization.k8s.io

---
# Generate RoleBinding for team based on namespace label
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-team-rolebinding
  annotations:
    policies.kyverno.io/title: Generate Team RoleBinding
    policies.kyverno.io/category: Multi-Tenancy
    policies.kyverno.io/subject: RoleBinding
    policies.kyverno.io/description: >-
      Creates RoleBindings for teams based on namespace labels.
spec:
  rules:
    - name: generate-team-admin
      match:
        any:
          - resources:
              kinds:
                - Namespace
              selector:
                matchExpressions:
                  - key: team
                    operator: Exists
      generate:
        apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        name: team-admin
        namespace: "{{request.object.metadata.name}}"
        synchronize: true
        data:
          metadata:
            labels:
              generated-by: kyverno
              team: "{{request.object.metadata.labels.team}}"
          subjects:
            - kind: Group
              name: "team-{{request.object.metadata.labels.team}}"
              apiGroup: rbac.authorization.k8s.io
          roleRef:
            kind: ClusterRole
            name: edit
            apiGroup: rbac.authorization.k8s.io

---
# Generate ConfigMap with namespace metadata
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-namespace-config
  annotations:
    policies.kyverno.io/title: Generate Namespace Config
    policies.kyverno.io/category: Multi-Tenancy
    policies.kyverno.io/subject: ConfigMap
    policies.kyverno.io/description: >-
      Creates a ConfigMap containing namespace metadata for applications
      that need to know their context.
spec:
  rules:
    - name: generate-ns-config
      match:
        any:
          - resources:
              kinds:
                - Namespace
      exclude:
        any:
          - resources:
              names:
                - kube-*
                - default
                - kyverno
      generate:
        apiVersion: v1
        kind: ConfigMap
        name: namespace-config
        namespace: "{{request.object.metadata.name}}"
        synchronize: true
        data:
          data:
            NAMESPACE_NAME: "{{request.object.metadata.name}}"
            CREATED_BY: "{{request.userInfo.username}}"
            ENVIRONMENT: "{{request.object.metadata.labels.environment || 'unknown'}}"
            TEAM: "{{request.object.metadata.labels.team || 'unknown'}}"

---
# Generate ServiceAccount with specific permissions
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-app-serviceaccount
  annotations:
    policies.kyverno.io/title: Generate Application ServiceAccount
    policies.kyverno.io/category: Multi-Tenancy
    policies.kyverno.io/subject: ServiceAccount
    policies.kyverno.io/description: >-
      Creates a default application ServiceAccount with automount disabled.
spec:
  rules:
    - name: generate-app-sa
      match:
        any:
          - resources:
              kinds:
                - Namespace
      exclude:
        any:
          - resources:
              names:
                - kube-*
                - default
                - kyverno
      generate:
        apiVersion: v1
        kind: ServiceAccount
        name: app-service-account
        namespace: "{{request.object.metadata.name}}"
        synchronize: true
        data:
          metadata:
            labels:
              generated-by: kyverno
          automountServiceAccountToken: false
