# Secrets Management and External Secrets Policies
# Policies for secrets management and external secrets operators

---
# Validate ExternalSecret configurations
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: validate-externalsecret
  annotations:
    policies.kyverno.io/title: Validate ExternalSecret
    policies.kyverno.io/category: Secrets Management
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: ExternalSecret
    policies.kyverno.io/description: >-
      Validates External Secrets Operator configurations.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-secret-store-ref
      match:
        any:
          - resources:
              kinds:
                - ExternalSecret
      validate:
        message: "ExternalSecret must reference a SecretStore or ClusterSecretStore."
        pattern:
          spec:
            secretStoreRef:
              name: "?*"
              kind: "SecretStore | ClusterSecretStore"
    - name: require-refresh-interval
      match:
        any:
          - resources:
              kinds:
                - ExternalSecret
      validate:
        message: "ExternalSecret should specify refreshInterval."
        pattern:
          spec:
            refreshInterval: "?*"

---
# Restrict SecretStore providers
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-secretstore-providers
  annotations:
    policies.kyverno.io/title: Restrict SecretStore Providers
    policies.kyverno.io/category: Secrets Management
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: SecretStore, ClusterSecretStore
    policies.kyverno.io/description: >-
      Restricts which secret store providers can be used.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: allow-only-approved-providers
      match:
        any:
          - resources:
              kinds:
                - SecretStore
                - ClusterSecretStore
      validate:
        message: "Only AWS Secrets Manager, HashiCorp Vault, and Azure Key Vault are approved."
        anyPattern:
          - spec:
              provider:
                aws:
                  service: SecretsManager
          - spec:
              provider:
                vault:
                  server: "?*"
          - spec:
              provider:
                azurekv:
                  vaultUrl: "?*"

---
# Disallow hardcoded secrets in ConfigMaps
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-secrets-in-configmaps
  annotations:
    policies.kyverno.io/title: Disallow Secrets in ConfigMaps
    policies.kyverno.io/category: Secrets Management
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: ConfigMap
    policies.kyverno.io/description: >-
      Prevents storing sensitive data in ConfigMaps.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: check-for-secrets
      match:
        any:
          - resources:
              kinds:
                - ConfigMap
      validate:
        message: "ConfigMaps should not contain sensitive data. Use Secrets instead."
        deny:
          conditions:
            any:
              - key: "{{ request.object.data.keys(@) }}"
                operator: AnyIn
                value:
                  - password
                  - secret
                  - api_key
                  - apikey
                  - api-key
                  - token
                  - credentials
                  - private_key
                  - privatekey

---
# Require encryption for secrets
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-sealed-secrets
  annotations:
    policies.kyverno.io/title: Require Sealed Secrets
    policies.kyverno.io/category: Secrets Management
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Secret
    policies.kyverno.io/description: >-
      In GitOps workflows, plain Secrets should be avoided in favor of
      SealedSecrets or ExternalSecrets.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: prefer-external-secrets
      match:
        any:
          - resources:
              kinds:
                - Secret
      exclude:
        any:
          - resources:
              names:
                - "*-token-*"
                - "sh.helm.release.*"
              annotations:
                sealedsecrets.bitnami.com/managed: "true"
              selector:
                matchLabels:
                  app.kubernetes.io/managed-by: "external-secrets"
      preconditions:
        all:
          - key: "{{ request.object.type }}"
            operator: NotEquals
            value: "kubernetes.io/service-account-token"
      validate:
        message: "Consider using ExternalSecrets or SealedSecrets for GitOps workflows."
        deny:
          conditions:
            all:
              - key: "{{ request.object.metadata.annotations.\"managed-by\" || '' }}"
                operator: NotEquals
                value: "external-secrets"

---
# Add secret rotation annotation
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-secret-rotation-annotation
  annotations:
    policies.kyverno.io/title: Add Secret Rotation Annotation
    policies.kyverno.io/category: Secrets Management
    policies.kyverno.io/subject: Secret
    policies.kyverno.io/description: >-
      Adds annotations to track secret creation and rotation requirements.
spec:
  rules:
    - name: add-rotation-annotation
      match:
        any:
          - resources:
              kinds:
                - Secret
      exclude:
        any:
          - resources:
              names:
                - "*-token-*"
      preconditions:
        all:
          - key: "{{ request.object.type }}"
            operator: NotEquals
            value: "kubernetes.io/service-account-token"
      mutate:
        patchStrategicMerge:
          metadata:
            annotations:
              +(secrets.company.com/created-at): "{{ time_now_utc() }}"
              +(secrets.company.com/rotate-by): "90d"

---
# Validate Vault sidecar injection
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: validate-vault-injection
  annotations:
    policies.kyverno.io/title: Validate Vault Sidecar Injection
    policies.kyverno.io/category: Secrets Management, Vault
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Validates pods using Vault Agent sidecar injection.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-vault-role
      match:
        any:
          - resources:
              kinds:
                - Pod
              annotations:
                vault.hashicorp.com/agent-inject: "true"
      validate:
        message: "Pods with Vault injection must specify a role."
        pattern:
          metadata:
            annotations:
              vault.hashicorp.com/role: "?*"

---
# Add Vault annotations automatically
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-vault-annotations
  annotations:
    policies.kyverno.io/title: Add Vault Annotations
    policies.kyverno.io/category: Secrets Management, Vault
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Adds default Vault sidecar injection annotations.
spec:
  rules:
    - name: add-vault-defaults
      match:
        any:
          - resources:
              kinds:
                - Pod
              selector:
                matchLabels:
                  vault-enabled: "true"
      mutate:
        patchStrategicMerge:
          metadata:
            annotations:
              +(vault.hashicorp.com/agent-inject): "true"
              +(vault.hashicorp.com/agent-pre-populate-only): "true"
              +(vault.hashicorp.com/agent-init-first): "true"

---
# Require secret encryption at rest annotation
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-encryption-annotation
  annotations:
    policies.kyverno.io/title: Require Encryption Annotation
    policies.kyverno.io/category: Secrets Management
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Secret
    policies.kyverno.io/description: >-
      Ensures secrets have encryption classification annotation.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-classification
      match:
        any:
          - resources:
              kinds:
                - Secret
              namespaces:
                - production
                - prod
      exclude:
        any:
          - resources:
              names:
                - "*-token-*"
                - "sh.helm.release.*"
      preconditions:
        all:
          - key: "{{ request.object.type }}"
            operator: NotEquals
            value: "kubernetes.io/service-account-token"
      validate:
        message: "Production secrets must have data classification annotation."
        pattern:
          metadata:
            annotations:
              security.company.com/classification: "confidential | internal | public"
