# Best Practices Policies Collection
# Comprehensive set of Kubernetes best practices enforcement

---
# Disallow empty ingress host
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-empty-ingress-host
  annotations:
    policies.kyverno.io/title: Disallow Empty Ingress Host
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Ingress
    policies.kyverno.io/description: >-
      An Ingress resource with empty host field can route traffic to backend
      services without proper hostname validation. This policy requires all
      Ingress resources to have a non-empty host field.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: disallow-empty-host
      match:
        any:
          - resources:
              kinds:
                - Ingress
      validate:
        message: "Ingress must have a non-empty host field."
        pattern:
          spec:
            rules:
              - host: "?*"

---
# Require TLS for Ingress
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-ingress-tls
  annotations:
    policies.kyverno.io/title: Require Ingress TLS
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Ingress
    policies.kyverno.io/description: >-
      All production Ingress resources should use TLS for encryption.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-tls
      match:
        any:
          - resources:
              kinds:
                - Ingress
              namespaces:
                - production
                - prod
      validate:
        message: "Production Ingress must use TLS."
        pattern:
          spec:
            tls:
              - hosts:
                  - "?*"
                secretName: "?*"

---
# Require deployment strategy
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-deployment-strategy
  annotations:
    policies.kyverno.io/title: Require Deployment Strategy
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: low
    policies.kyverno.io/subject: Deployment
    policies.kyverno.io/description: >-
      Deployments should have an explicit rolling update strategy.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-rolling-update
      match:
        any:
          - resources:
              kinds:
                - Deployment
      validate:
        message: "Deployment must specify a rolling update strategy."
        pattern:
          spec:
            strategy:
              type: RollingUpdate
              rollingUpdate:
                maxSurge: "?*"
                maxUnavailable: "?*"

---
# Require pod anti-affinity for HA
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-pod-antiaffinity
  annotations:
    policies.kyverno.io/title: Require Pod Anti-Affinity
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Deployment
    policies.kyverno.io/description: >-
      High availability deployments should use pod anti-affinity to spread
      replicas across nodes.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-antiaffinity
      match:
        any:
          - resources:
              kinds:
                - Deployment
              namespaces:
                - production
                - prod
      preconditions:
        all:
          - key: "{{ request.object.spec.replicas }}"
            operator: GreaterThan
            value: 1
      validate:
        message: "Production deployments with multiple replicas must have pod anti-affinity."
        pattern:
          spec:
            template:
              spec:
                affinity:
                  podAntiAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                      - weight: ">0"

---
# Require HPA for production deployments
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-hpa
  annotations:
    policies.kyverno.io/title: Require HPA
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: low
    policies.kyverno.io/subject: Deployment
    policies.kyverno.io/description: >-
      Production deployments should have an associated HorizontalPodAutoscaler.
spec:
  validationFailureAction: Audit
  background: false
  rules:
    - name: require-hpa
      match:
        any:
          - resources:
              kinds:
                - Deployment
              namespaces:
                - production
                - prod
      preconditions:
        all:
          - key: "{{ request.operation || 'BACKGROUND' }}"
            operator: Equals
            value: CREATE
      context:
        - name: hpa_count
          apiCall:
            urlPath: "/apis/autoscaling/v2/namespaces/{{request.namespace}}/horizontalpodautoscalers"
            jmesPath: "items[?spec.scaleTargetRef.name == '{{request.object.metadata.name}}'] | length(@)"
      validate:
        message: "Production deployments require an associated HPA."
        deny:
          conditions:
            any:
              - key: "{{ hpa_count }}"
                operator: LessThan
                value: 1

---
# Disallow ClusterIP None for headless services unless needed
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-headless-services
  annotations:
    policies.kyverno.io/title: Restrict Headless Services
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: low
    policies.kyverno.io/subject: Service
    policies.kyverno.io/description: >-
      Headless services (clusterIP: None) should only be used when necessary.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: restrict-headless
      match:
        any:
          - resources:
              kinds:
                - Service
      exclude:
        any:
          - resources:
              selector:
                matchLabels:
                  allow-headless: "true"
      validate:
        message: "Headless services require 'allow-headless: true' label."
        pattern:
          spec:
            clusterIP: "!None"

---
# Require annotations for external DNS
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-external-dns-annotation
  annotations:
    policies.kyverno.io/title: Require External DNS Annotation
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: low
    policies.kyverno.io/subject: Service
    policies.kyverno.io/description: >-
      LoadBalancer services should have external-dns annotations for DNS
      management.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-dns-annotation
      match:
        any:
          - resources:
              kinds:
                - Service
      preconditions:
        all:
          - key: "{{ request.object.spec.type }}"
            operator: Equals
            value: LoadBalancer
      validate:
        message: "LoadBalancer services must have external-dns hostname annotation."
        pattern:
          metadata:
            annotations:
              external-dns.alpha.kubernetes.io/hostname: "?*"

---
# Require termination grace period
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-termination-grace-period
  annotations:
    policies.kyverno.io/title: Require Termination Grace Period
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: low
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Pods should have adequate termination grace period for graceful shutdown.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-grace-period
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Pods must have terminationGracePeriodSeconds >= 30."
        pattern:
          spec:
            terminationGracePeriodSeconds: ">=30"

---
# Disallow node selectors that are too specific
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: validate-node-selector
  annotations:
    policies.kyverno.io/title: Validate Node Selector
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: low
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Prevents pods from using node selectors that specify specific node names.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: no-specific-node
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Pods cannot target specific nodes by name."
        pattern:
          spec:
            =(nodeSelector):
              X(kubernetes.io/hostname): "*"
