# Cert-Manager and TLS Policies
# Policies for certificate management and TLS configuration

---
# Validate Certificate resources
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: validate-certificate
  annotations:
    policies.kyverno.io/title: Validate Certificate Resources
    policies.kyverno.io/category: Cert-Manager, TLS
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Certificate
    policies.kyverno.io/description: >-
      Validates cert-manager Certificate resources for security best practices.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-minimum-duration
      match:
        any:
          - resources:
              kinds:
                - Certificate
      validate:
        message: "Certificate duration must be at least 24 hours."
        pattern:
          spec:
            duration: ">=24h"
    - name: require-renew-before
      match:
        any:
          - resources:
              kinds:
                - Certificate
      validate:
        message: "Certificate renewBefore must be set."
        pattern:
          spec:
            renewBefore: "?*"
    - name: require-private-key-algorithm
      match:
        any:
          - resources:
              kinds:
                - Certificate
      validate:
        message: "Certificate private key must use RSA (2048+) or ECDSA."
        pattern:
          spec:
            privateKey:
              algorithm: "RSA | ECDSA"

---
# Validate ClusterIssuer configurations
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: validate-clusterissuer
  annotations:
    policies.kyverno.io/title: Validate ClusterIssuer
    policies.kyverno.io/category: Cert-Manager, TLS
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: ClusterIssuer
    policies.kyverno.io/description: >-
      Validates ClusterIssuer configurations.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-acme-server
      match:
        any:
          - resources:
              kinds:
                - ClusterIssuer
      preconditions:
        all:
          - key: "{{ request.object.spec.acme || '' }}"
            operator: NotEquals
            value: ""
      validate:
        message: "ACME ClusterIssuer must use Let's Encrypt production or staging server."
        pattern:
          spec:
            acme:
              server: "https://acme-v02.api.letsencrypt.org/* | https://acme-staging-v02.api.letsencrypt.org/*"

---
# Require TLS secrets for production Ingress
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-tls-secret
  annotations:
    policies.kyverno.io/title: Require TLS Secret
    policies.kyverno.io/category: TLS, Security
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Ingress
    policies.kyverno.io/description: >-
      Production Ingress must reference a TLS secret.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-tls
      match:
        any:
          - resources:
              kinds:
                - Ingress
              namespaces:
                - production
                - prod
      validate:
        message: "Production Ingress must have TLS configuration with secretName."
        pattern:
          spec:
            tls:
              - secretName: "?*"
                hosts:
                  - "?*"

---
# Generate Certificate for Ingress
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-certificate-for-ingress
  annotations:
    policies.kyverno.io/title: Generate Certificate for Ingress
    policies.kyverno.io/category: Cert-Manager, TLS
    policies.kyverno.io/subject: Certificate
    policies.kyverno.io/description: >-
      Automatically generates cert-manager Certificate for Ingress resources.
spec:
  rules:
    - name: generate-cert
      match:
        any:
          - resources:
              kinds:
                - Ingress
              annotations:
                cert-manager.io/cluster-issuer: "?*"
      preconditions:
        all:
          - key: "{{ request.object.spec.tls[0].secretName || '' }}"
            operator: NotEquals
            value: ""
      generate:
        apiVersion: cert-manager.io/v1
        kind: Certificate
        name: "{{request.object.metadata.name}}-tls"
        namespace: "{{request.namespace}}"
        synchronize: true
        data:
          spec:
            secretName: "{{request.object.spec.tls[0].secretName}}"
            issuerRef:
              name: "{{request.object.metadata.annotations.\"cert-manager.io/cluster-issuer\"}}"
              kind: ClusterIssuer
            dnsNames: "{{request.object.spec.tls[0].hosts}}"

---
# Validate TLS version in secrets
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: validate-tls-secret-data
  annotations:
    policies.kyverno.io/title: Validate TLS Secret Data
    policies.kyverno.io/category: TLS, Security
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Secret
    policies.kyverno.io/description: >-
      Validates that TLS secrets contain required data.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-tls-data
      match:
        any:
          - resources:
              kinds:
                - Secret
      preconditions:
        all:
          - key: "{{ request.object.type }}"
            operator: Equals
            value: "kubernetes.io/tls"
      validate:
        message: "TLS secrets must contain tls.crt and tls.key."
        pattern:
          data:
            tls.crt: "?*"
            tls.key: "?*"

---
# Add cert-manager annotations to Ingress
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-certmanager-annotations
  annotations:
    policies.kyverno.io/title: Add Cert-Manager Annotations
    policies.kyverno.io/category: Cert-Manager, TLS
    policies.kyverno.io/subject: Ingress
    policies.kyverno.io/description: >-
      Adds default cert-manager annotations to Ingress resources.
spec:
  rules:
    - name: add-cluster-issuer
      match:
        any:
          - resources:
              kinds:
                - Ingress
      preconditions:
        all:
          - key: "{{ request.object.spec.tls || '' | length(@) }}"
            operator: GreaterThan
            value: 0
      mutate:
        patchStrategicMerge:
          metadata:
            annotations:
              +(cert-manager.io/cluster-issuer): "letsencrypt-prod"

---
# Restrict certificate issuers
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-certificate-issuers
  annotations:
    policies.kyverno.io/title: Restrict Certificate Issuers
    policies.kyverno.io/category: Cert-Manager, TLS
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Certificate
    policies.kyverno.io/description: >-
      Restricts which issuers can be used for certificates.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: restrict-issuers
      match:
        any:
          - resources:
              kinds:
                - Certificate
      validate:
        message: "Certificate must use an approved issuer."
        pattern:
          spec:
            issuerRef:
              name: "letsencrypt-prod | letsencrypt-staging | internal-ca"
              kind: "ClusterIssuer | Issuer"

---
# Require HTTPS redirect annotation
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-https-redirect
  annotations:
    policies.kyverno.io/title: Require HTTPS Redirect
    policies.kyverno.io/category: TLS, Security
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Ingress
    policies.kyverno.io/description: >-
      Ingress resources should redirect HTTP to HTTPS.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-ssl-redirect
      match:
        any:
          - resources:
              kinds:
                - Ingress
      preconditions:
        all:
          - key: "{{ request.object.spec.tls || '' | length(@) }}"
            operator: GreaterThan
            value: 0
      validate:
        message: "Ingress with TLS should enforce SSL redirect."
        anyPattern:
          - metadata:
              annotations:
                nginx.ingress.kubernetes.io/ssl-redirect: "true"
          - metadata:
              annotations:
                kubernetes.io/ingress.allow-http: "false"
