# Additional Validation Policies
# Collection of useful validation rules

---
# Require read-only root filesystem
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-ro-rootfs
  annotations:
    policies.kyverno.io/title: Require Read-Only Root Filesystem
    policies.kyverno.io/category: Pod Security Standards (Restricted)
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      A read-only root filesystem helps to enforce an immutable infrastructure
      strategy; the container only needs to write on mounted volumes.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: validate-readOnlyRootFilesystem
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Root filesystem must be read-only."
        pattern:
          spec:
            containers:
              - securityContext:
                  readOnlyRootFilesystem: true

---
# Disallow empty directory volumes with medium Memory
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-emptydir-memory
  annotations:
    policies.kyverno.io/title: Disallow EmptyDir Memory Medium
    policies.kyverno.io/category: Security
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod, Volume
    policies.kyverno.io/description: >-
      EmptyDir volumes with medium Memory can consume node memory.
      This policy restricts the use of memory-backed emptyDir volumes.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: validate-emptydir-medium
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "EmptyDir volumes with 'Memory' medium are not allowed."
        pattern:
          spec:
            =(volumes):
              - =(emptyDir):
                  =(medium): "!Memory"

---
# Restrict automounting of service account tokens
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-automount-sa-token
  annotations:
    policies.kyverno.io/title: Restrict Auto-Mount of Service Account Token
    policies.kyverno.io/category: Security
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Pods by default mount a service account token which can be used to
      interact with the Kubernetes API. This policy restricts auto-mounting
      of service account tokens.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: validate-automountServiceAccountToken
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: >-
          Pods must not automount service account tokens. Set
          automountServiceAccountToken to false.
        pattern:
          spec:
            automountServiceAccountToken: "false"

---
# Require PodDisruptionBudget for Deployments
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-pdb
  annotations:
    policies.kyverno.io/title: Require PodDisruptionBudget
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Deployment
    policies.kyverno.io/description: >-
      PodDisruptionBudgets are important for ensuring high availability
      during voluntary disruptions. This policy requires Deployments to
      have a matching PDB.
spec:
  validationFailureAction: Audit
  background: false
  rules:
    - name: require-pdb
      match:
        any:
          - resources:
              kinds:
                - Deployment
      preconditions:
        all:
          - key: "{{ request.operation || 'BACKGROUND' }}"
            operator: Equals
            value: CREATE
      context:
        - name: pdb_count
          apiCall:
            urlPath: "/apis/policy/v1/namespaces/{{request.namespace}}/poddisruptionbudgets"
            jmesPath: "items[?spec.selector.matchLabels == `{{request.object.spec.selector.matchLabels}}`] | length(@)"
      validate:
        message: "A PodDisruptionBudget is required for this Deployment."
        deny:
          conditions:
            any:
              - key: "{{ pdb_count }}"
                operator: LessThan
                value: 1

---
# Disallow default service account
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-default-serviceaccount
  annotations:
    policies.kyverno.io/title: Disallow Default ServiceAccount
    policies.kyverno.io/category: Security
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      The default service account should not be used to prevent
      accidental access to cluster resources.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: validate-serviceaccount
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Using the default service account is not allowed."
        pattern:
          spec:
            =(serviceAccountName): "!default"

---
# Require replica count for Deployments
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-minimum-replicas
  annotations:
    policies.kyverno.io/title: Require Minimum Replicas
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Deployment
    policies.kyverno.io/description: >-
      Production deployments should have multiple replicas for high availability.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: deployment-has-multiple-replicas
      match:
        any:
          - resources:
              kinds:
                - Deployment
              namespaces:
                - production
                - prod
      validate:
        message: "Production deployments must have at least 2 replicas."
        pattern:
          spec:
            replicas: ">1"

---
# Disallow secrets in environment variables
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: secrets-not-from-env-vars
  annotations:
    policies.kyverno.io/title: Disallow Secrets from Environment Variables
    policies.kyverno.io/category: Security
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Secrets should be mounted as volumes rather than exposed as environment
      variables to avoid accidental logging and exposure.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: secrets-not-from-env-vars
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Secrets must be mounted as volumes, not as environment variables."
        pattern:
          spec:
            containers:
              - name: "*"
                =(env):
                  - =(valueFrom):
                      X(secretKeyRef): "null"
