# Disallow Latest Tag Policy
# Prevents use of mutable 'latest' tag in container images
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-latest-tag
  annotations:
    policies.kyverno.io/title: Disallow Latest Tag
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      The ':latest' tag is mutable and can lead to unexpected errors if the
      image changes. A best practice is to use an immutable tag that corresponds
      to a specific version of an application Pod. This policy validates that 
      the image specifies a tag and that it is not called 'latest'.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-image-tag
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "An image tag is required."
        pattern:
          spec:
            containers:
              - image: "*:*"
    - name: validate-image-tag
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Using a mutable image tag e.g. 'latest' is not allowed."
        pattern:
          spec:
            containers:
              - image: "!*:latest"

---
# Extended version: Disallow latest tag for init containers and ephemeral containers
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-latest-tag-extended
  annotations:
    policies.kyverno.io/title: Disallow Latest Tag (Extended)
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Extends the latest tag check to include init containers and ephemeral containers.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: validate-containers
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Using 'latest' tag is not allowed for containers."
        pattern:
          spec:
            containers:
              - image: "!*:latest"
    - name: validate-init-containers
      match:
        any:
          - resources:
              kinds:
                - Pod
      preconditions:
        all:
          - key: "{{ request.object.spec.initContainers[] | length(@) }}"
            operator: GreaterThanOrEquals
            value: 1
      validate:
        message: "Using 'latest' tag is not allowed for init containers."
        pattern:
          spec:
            initContainers:
              - image: "!*:latest"
